### ISSUE TITLE
Default virtuals is missing when from the populated object

### ISSUE THREAD

**Issue by PanJ** [buunguyen/mongoose-deep-populate#10]
version 1.0.1 have the issue that setting
```javascript
schema.set('toJSON', { virtuals: true });
```
will not include virtuals on the populated object.

**Comment by buunguyen** [comment]
Does the built-in `populate` include virtuals?

**Comment by PanJ** [comment]
I just confirmed that built-in `populate` does not include virtuals but `1.0.0` does include virtuals.

Then, I would to like to request new feature that provides an option to include virtuals on deep-polulate.

**Comment by buunguyen** [comment]
1.0.0 worked because it didn't apply `lean`. 1.0.1 applies `lean`, if you turn it on, then you won't get virtuals by default. That's by design and expected. If you want virtuals, set it in the schema option for `toObject`. See the [Mongoose doc](http://mongoosejs.com/docs/guide.html#virtuals) for details.
