### ISSUE TITLE
Improve the plugin API

### ISSUE THREAD

**Issue by stevenfrog** [buunguyen/mongoose-deep-populate#4]
This is not a bug report, but suggestion.
1. please do not use ',', use white space instead, because mongoose populate use white space

2.
I need use it like this:
```
Profile.find().exec(function(err, tmpItems) {
        Profile.deepPopulate(tmpItems, 'salesDistrict, division, salesDistrict.division', function(err, items) {
```
 
But it so similar like my original code:
```
Profile.find().populate("salesDistrict division").exec(function(err, tmpItems) {

    Profile.populate(tmpItems, {path: 'salesDistrict.division'}, function(err, items) {
```

If you can improve your code and use as 'populate' is better:
```
Profile.find().populate("salesDistrict division salesDistrict.division").exec(function(err, tmpItems) {
```

**Comment by buunguyen** [comment]
These are good suggestions, thank you!  I've implemented both.

Regarding the second issue, instead of monkey-patching the existing `populate` method, I add `deepPopulate` instead. This is to avoid confusion as the two have quite different semantics when coming to option handling. 

Also, while the implementation takes care of the use case you mentioned, I'm not sure if it could cause surprising behavior in other use cases, e.g. when combining with other methods of `Query`. Therefore, I won't publish to version until feeling certain that it doesn't do harm.

Please give it a try and let me know your feedback.

**Comment by stevenfrog** [comment]
I have just three layer data, and I will worked on a very complicated data. 
After you finished, I will try your plugin on it.

I use current codes to do deep populate:
```
getAll:function (callback) {
    async.waterfall([
        function(cb) {
            Profile.find().populate("salesDistrict division").exec(cb);
        },
        function(tmpItems, cb) {
            Profile.populate(tmpItems, {
                path: 'salesDistrict.division'
            }, cb);
        }
    ], function(err, items) {
        callback(err, mapToJSON(items));
    });
  }
```
With sample data, it works well.
If data become more complicated, I may use a helper function to refactor it.
like 'getDeepJSON(Profile, criteria, ["salesDistrict division", "salesDistrict.division"])'

Your implementation maybe more elegant.

**Comment by buunguyen** [comment]
Yes, with the new implementation, you could just do:

```javascript
Profile.find().populate("division salesDistrict.division").exec(function (err, items) { 
  cb(err, mapToJSON(items)) 
});
```

**Comment by buunguyen** [comment]
I've tested and thought about this a bit more myself. I can't think of a way where it could break other code. Therefore, published to NPM.

**Comment by stevenfrog** [comment]
Well done, it works as expected.
